"""Implements: FA74 (Provenienz und Laufmetriken im RDF-Export, PROV-O).

Contract tests: a run through ``api.run`` writes, in addition to the FA13/FA65
triples, the result as ``prov:Entity`` generated by the activity of the producing
step, one ``prov:Activity`` per step on the path (operation, parameters as
``rdf:JSON``, ``prov:used``), each source layer as ``prov:Entity`` (source type,
parameters such as OSM tags, licence, source CRS, feature count, bounds), the run
(scenario, region, working CRS, start/end, version) and simple result metrics.
Deterministic except the timestamps; ``provenance: false`` switches it off; only
additive triples. The SPARQL example of ``docs/provenienz_rdf.md`` runs here.
Offline: the OSM layer is replaced by a connector override.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import geopandas as gpd
import pytest
from rdflib import RDF, XSD, Graph, Literal
from rdflib.compare import isomorphic
from rdflib.namespace import DCAT, DCTERMS, PROV

from geofact import api
from geofact.builtin.outputs.rdf import GEOFACT, GEOFACT_VOCAB, build_graph

REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "tests" / "fixtures"
REGION = "13.60,51.01,13.94,51.15"


@pytest.fixture(autouse=True)
def _isolated(tmp_path, monkeypatch):
    monkeypatch.setenv("GEOFACT_SNAPSHOT_DIR", str(tmp_path / "snapshots"))
    monkeypatch.chdir(tmp_path)


def _lines(_layer) -> gpd.GeoDataFrame:
    return gpd.read_file(FIXTURES / "power_lines.geojson")


OVERRIDE = {"leitungen": _lines}


def _config(rdf_output: dict | None = None, *, buffer_km: float = 1.0) -> dict:
    output = {"type": "rdf", "source": "schnitt", "path": "o.ttl"}
    output.update(rdf_output or {})
    return {
        "scenario": {"name": "Herkunft Dresden", "region": REGION},
        "layers": [
            {
                "id": "umspannwerke",
                "source": "file",
                "data_type": "vector",
                "path": str(FIXTURES / "substations.geojson"),
                "license": {"name": "CC-BY-4.0", "attribution": "Stadt Beispiel"},
            },
            {"id": "leitungen", "source": "osm", "tags": [{"power": "line"}]},
            {
                "id": "ungenutzt",
                "source": "file",
                "data_type": "vector",
                "path": str(FIXTURES / "substations.geojson"),
            },
        ],
        "steps": [
            {
                "id": "puffer",
                "op": "buffer",
                "inputs": {"geometry": "umspannwerke"},
                "params": {"radius_km": buffer_km},
            },
            {
                "id": "schnitt",
                "op": "clip",
                "inputs": {"features": "leitungen", "mask": "puffer"},
            },
        ],
        "output": [output],
    }


def _run(tmp_path, config: dict, name: str = "out") -> Graph:
    report = api.run(
        api.load_scenario(config), out_dir=tmp_path / name, connector_override=OVERRIDE
    )
    assert not report.skipped_outputs, report.skipped_outputs
    path = tmp_path / name / config["output"][0]["path"]
    return Graph().parse(path, format="turtle")


def _json(graph: Graph, subject, predicate=GEOFACT_VOCAB.parameters):
    [value] = list(graph.objects(subject, predicate))
    assert value.datatype == RDF.JSON
    return json.loads(str(value))


def test_fa74_result_is_a_prov_entity_generated_by_the_producing_step(tmp_path):
    graph = _run(tmp_path, _config())
    dataset, activity = GEOFACT["dataset/schnitt"], GEOFACT["activity/schnitt"]
    assert (dataset, RDF.type, PROV.Entity) in graph
    assert (dataset, RDF.type, DCAT.Dataset) in graph
    assert (dataset, PROV.wasGeneratedBy, activity) in graph
    assert (activity, RDF.type, PROV.Activity) in graph
    assert (activity, GEOFACT_VOCAB.operation, Literal("clip")) in graph
    assert set(graph.objects(activity, PROV.used)) == {
        GEOFACT["source/leitungen"],
        GEOFACT["entity/puffer"],
    }


def test_fa74_every_step_on_the_path_is_an_activity_with_its_parameters(tmp_path):
    graph = _run(tmp_path, _config(buffer_km=0.5))
    puffer = GEOFACT["activity/puffer"]
    assert (GEOFACT["entity/puffer"], PROV.wasGeneratedBy, puffer) in graph
    params = _json(graph, puffer)
    assert params["radius_km"] == 0.5
    assert (puffer, PROV.used, GEOFACT["source/umspannwerke"]) in graph
    activities = set(graph.subjects(RDF.type, PROV.Activity))
    run = _run_uri(graph)
    assert activities == {puffer, GEOFACT["activity/schnitt"], run}
    assert (puffer, GEOFACT_VOCAB.run, run) in graph


def test_fa74_source_layers_carry_type_parameters_license_crs_count_and_bounds(
    tmp_path,
):
    graph = _run(tmp_path, _config())
    osm, file_layer = GEOFACT["source/leitungen"], GEOFACT["source/umspannwerke"]
    assert (osm, GEOFACT_VOCAB.sourceType, Literal("osm")) in graph
    assert _json(graph, osm)["tags"] == [{"power": "line"}]
    assert (osm, DCTERMS.license, Literal("ODbL-1.0")) not in graph  # URL wins
    assert any("OpenStreetMap" in str(v) for v in graph.objects(osm, DCTERMS.rights))
    assert (file_layer, GEOFACT_VOCAB.sourceType, Literal("file")) in graph
    assert _json(graph, file_layer)["path"].endswith("substations.geojson")
    assert (file_layer, DCTERMS.license, Literal("CC-BY-4.0")) in graph
    assert (file_layer, GEOFACT_VOCAB.sourceCrs, Literal("EPSG:4326")) in graph
    [count] = list(graph.objects(file_layer, GEOFACT_VOCAB.featureCount))
    assert count.datatype == XSD.integer and int(count) > 0
    bounds = _json(graph, file_layer, GEOFACT_VOCAB.bounds)
    assert len(bounds) == 4 and bounds[0] < bounds[2]
    assert str(next(graph.objects(file_layer, GEOFACT_VOCAB.boundsCrs))).startswith(
        "EPSG:326"
    )
    # a layer the plan never loads is not part of the provenance (lazy loading)
    assert (GEOFACT["source/ungenutzt"], None, None) not in graph


def test_fa74_run_metadata_and_result_metrics(tmp_path):
    graph = _run(tmp_path, _config())
    run = _run_uri(graph)
    assert (run, DCTERMS.title, Literal("Herkunft Dresden")) in graph
    assert (run, GEOFACT_VOCAB.region, Literal(REGION)) in graph
    assert str(next(graph.objects(run, GEOFACT_VOCAB.workingCrs))).startswith(
        "EPSG:326"
    )
    for predicate in (PROV.startedAtTime, PROV.endedAtTime):
        [stamp] = list(graph.objects(run, predicate))
        assert stamp.datatype == XSD.dateTime and re.match(
            r"\d{4}-\d\d-\d\dT", str(stamp)
        )
    agent = next(graph.objects(run, PROV.wasAssociatedWith))
    assert (agent, RDF.type, PROV.SoftwareAgent) in graph
    assert list(graph.objects(agent, GEOFACT_VOCAB.version))
    dataset = GEOFACT["dataset/schnitt"]
    [count] = list(graph.objects(dataset, GEOFACT_VOCAB.featureCount))
    features = set(graph.subjects(DCTERMS.isPartOf, dataset))
    assert int(count) == len(features) > 0


def test_fa74_numeric_columns_get_min_max_mean(tmp_path):
    graph = build_graph(
        gpd.GeoDataFrame(
            {
                "v": [1.0, 3.0, float("nan")],
                "flag": [True, False, True],
                "name": ["a", "b", "c"],
            },
            geometry=gpd.points_from_xy([13, 13.1, 13.2], [51, 51, 51]),
            crs="EPSG:4326",
        ),
        "x",
        lineage=_lineage_for("x"),
    )
    dataset = GEOFACT["dataset/x"]
    [statistic] = list(graph.objects(dataset, GEOFACT_VOCAB.statistic))
    assert (statistic, GEOFACT_VOCAB.column, Literal("v")) in graph
    values = {
        p: float(o)
        for p, o in graph.predicate_objects(statistic)
        if p != GEOFACT_VOCAB.column
    }
    assert values == {
        GEOFACT_VOCAB.min: 1.0,
        GEOFACT_VOCAB.max: 3.0,
        GEOFACT_VOCAB.mean: 2.0,
    }


def test_fa74_empty_result_has_count_zero_and_no_statistics(tmp_path):
    empty = gpd.GeoDataFrame({"v": []}, geometry=[], crs="EPSG:4326")
    graph = build_graph(empty, "x", lineage=_lineage_for("x"))
    assert (
        GEOFACT["dataset/x"],
        GEOFACT_VOCAB.featureCount,
        Literal(0, datatype=XSD.integer),
    ) in graph
    assert not list(graph.objects(GEOFACT["dataset/x"], GEOFACT_VOCAB.statistic))


def _lineage_for(node_id: str):
    from geofact.core.provenance import LineageNode, RunLineage

    return RunLineage(
        scenario_name="S",
        region="r",
        working_crs=None,
        started_at=None,
        finished_at=None,
        version="0",
        nodes={
            node_id: LineageNode(
                id=node_id, kind="step", block="buffer", parameters={"radius_km": 1}
            )
        },
    )


def _run_uri(graph: Graph):
    [run] = list(graph.subjects(RDF.type, GEOFACT_VOCAB.Run))
    assert str(run).startswith(str(GEOFACT["run/Herkunft-Dresden/"]))
    return run


def _without_run_specifics(graph: Graph) -> Graph:
    """Drop what legitimately differs between runs: the run URI and timestamps."""
    run = _run_uri(graph)
    for triple in list(graph.triples((run, None, None))):
        graph.remove(triple)
    for triple in list(graph.triples((None, None, run))):
        graph.remove(triple)
    return graph


def test_fa74_graph_is_deterministic_except_the_run_node(tmp_path):
    first = _run(tmp_path, _config(), "a")
    second = _run(tmp_path, _config(), "b")
    assert isomorphic(_without_run_specifics(first), _without_run_specifics(second))


def test_fa74_run_uri_is_unique_per_run_and_dataset_uris_stay_stable(tmp_path):
    first = _run(tmp_path, _config(), "a")
    second = _run(tmp_path, _config(), "b")
    assert _run_uri(first) != _run_uri(second)
    assert (GEOFACT["dataset/schnitt"], RDF.type, None) in first
    assert set(first.subjects(RDF.type, PROV.Entity)) == set(
        second.subjects(RDF.type, PROV.Entity)
    )


def test_fa74_provenance_triples_are_only_additive_and_can_be_switched_off(tmp_path):
    with_provenance = _run(tmp_path, _config(), "an")
    without = _run(tmp_path, _config({"provenance": False}), "aus")
    assert not list(without.triples((None, RDF.type, PROV.Activity)))
    assert not list(without.triples((None, GEOFACT_VOCAB.parameters, None)))
    # every FA13/FA65 triple stays; FA74 only adds (blank nodes: none without provenance)
    assert set(without) <= set(with_provenance)


def test_fa74_step_and_layer_warnings_are_attached_to_their_nodes():
    from geofact.engine.events import RunWarning
    from geofact.engine.outputs import run_lineage

    document = api.load_scenario(_config())
    result = api.run(document, connector_override=OVERRIDE).result
    result.warnings = [
        RunWarning(message="Maske leer", category="EmptyMaskWarning", step="schnitt"),
        RunWarning(
            message="Snapshot alt",
            category="SnapshotNotice",
            layer="leitungen",
            step="schnitt",
        ),
        RunWarning(message="Region groß", category="RegionWarning"),
    ]
    lineage = run_lineage(document.scenario, result)
    graph = build_graph(result.store["schnitt"], "schnitt", lineage=lineage)
    assert set(graph.objects(GEOFACT["activity/schnitt"], GEOFACT_VOCAB.warning)) == {
        Literal("EmptyMaskWarning: Maske leer"),
    }
    assert set(graph.objects(GEOFACT["source/leitungen"], GEOFACT_VOCAB.warning)) == {
        Literal("SnapshotNotice: Snapshot alt"),
    }
    assert not list(graph.objects(GEOFACT["activity/puffer"], GEOFACT_VOCAB.warning))


def _sparql_example() -> str:
    text = (REPO / "docs" / "provenienz_rdf.md").read_text(encoding="utf-8")
    [query] = re.findall(r"```sparql\n(.*?)```", text, flags=re.S)[:1]
    return query


def test_fa74_documented_sparql_finds_the_osm_tags_and_step_parameters_of_a_feature(
    tmp_path,
):
    graph = _run(tmp_path, _config(buffer_km=0.75))
    feature = next(iter(graph.subjects(DCTERMS.isPartOf, GEOFACT["dataset/schnitt"])))
    query = _sparql_example().replace(
        "<https://geofact.example.org/resource/schnitt/0>", f"<{feature}>"
    )
    rows = {
        (str(row.kind), str(row.block), str(row.parameters))
        for row in graph.query(query)
    }
    blocks = {(kind, block) for kind, block, _ in rows}
    assert {
        ("Quelle", "osm"),
        ("Quelle", "file"),
        ("Schritt", "buffer"),
        ("Schritt", "clip"),
    } <= blocks
    osm_params = next(json.loads(p) for kind, block, p in rows if block == "osm")
    assert osm_params["tags"] == [{"power": "line"}]
    buffer_params = next(json.loads(p) for kind, block, p in rows if block == "buffer")
    assert buffer_params["radius_km"] == 0.75
